import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";
// import Providers from "./providers";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const ttTravel = localFont({
  src: "./fonts/tt_travels/TT Travels Trial Regular.otf",
  variable: "--font-tt-travel",
  weight: "400 700",
});

export const metadata: Metadata = {
  title: "Game BIT | NFT Game Arena",
  description: "Generated by 42BKK Cadets",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ttTravel.variable} antialiased flex flex-col h-screen`}
      >
        {/* <Providers> */}
          <Header />
          <div className="flex flex-1 flex-col">
            {children}
          </div>
          <Footer />
        {/* </Providers> */}
      </body>
    </html>
  );
}
