"use client";

import { useLogin, usePrivy } from "@privy-io/react-auth";
import { Metadata } from 'next';
import { redirect } from 'next/navigation';
// import shortenAddress from './utils/index';
// import Image from 'next/image';
import Button from '@/components/Button';

const metadata: Metadata = {
  title: "Game BIT | NFT Game Arena",
  description: "Generated by 42BKK Cadets",
};

export default function Home() {
  const { logout, authenticated, ready, user, createWallet } = usePrivy();

  const { login } = useLogin({
    onComplete: async (user) => {
      console.log("login complete", user);
      if (!user.wallet) {
        const userWallet = await createWallet();
        console.log("new user wallet", userWallet);
      }
      redirect('/users');
    },
  });

  if (!ready) {
    return (
      <div className="flex justify-center items-center h-screen w-screen">
        <p>Loading...</p>
      </div>
    );
  }
  return (
    <div className='md:flex w-full h-full mx-auto'>
      <div className='flex-1 flex justify-center items-center space-x-4 px-5 rounded-full'>
        <div className="rounded-3xl shadow-xl p-4 text-center bg-gradient-primary w-80 h-80 flex justify-center items-center">
          {/* <Image src={Monkey} alt='monkey' /> */}
        </div>
        <div className="rounded-3xl shadow-xl p-4 text-center bg-gradient-primary w-80 h-80 flex justify-center items-center">
          {/* <Image src={Kaban} alt='Kaban' /> */}
        </div>
      </div>
      <div className='w-1/2 flex flex-col justify-center text-wrap px-5'>
        <p className='text-text-highlighted text-3xl mb-4'>
          Step into a world where fun meets rewards!
        </p>
        <p className='mb-4 text-white'>
          GameBIT is a Game Arena that lets you play exciting mini-games and win exclusive NFTs. Compete with other players in thrilling games like "Rock-Paper-Scissors," where your skills can earn you valuable digital collectibles.
        </p>
        <p className='text-[#26C6DA] mb-4 text-2xl'>
          Here is how it works:
        </p>
        <ul className='text-[#26C6DA] list-disc list-inside mb-4'>
          <li className='mb-2'>Join the Game: Enter a match by staking a small entry fee.</li>
          <li className='mb-2'>Compete and Win: Play against other players for a chance to win NFTs and reclaim your stake.</li>
          <li className='mb-2'>Fair and Transparent: Powered by blockchain, our platform ensures secure transactions and fair gameplay.</li>
        </ul>
        <div className="flex justify-between items-center">
          <p className='text-text-highlighted mb-4'>
            Ready to play and collect? Dive into the NFT Game Arena and turn your skills into rewards!
          </p>
          {authenticated && user && (
            <button
              onClick={() => logout()}
              className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
            >
              {/* {shortenAddress(user?.wallet!.address)} */}
              Logout
            </button>
          )}
          {!authenticated && (
            <Button onClick={() => login()}>
              Connect
            </Button>
          )}
        </div>
      </div>
  </div>
  );
}
